version: 2

jobs:

  # For documentation deployment. You'll need the following environment vars
  # in your Circle CI settings, otherwise this will not work.
  #
  # GH_NAME (your git username)
  # GH_EMAIL (your git email)
  # GH_TOKEN (the personal Git token with pushes enabled)
  deploy-doc:
    docker:
    - image: python:3.6
    working_directory: ~/gh_doc_automation
    steps:
    - checkout
    - run: ./build_tools/circle/before_install.sh
    - run: make doc-requirements
    - run: make install
    - run: ./build_tools/circle/build_push_doc.sh

workflows:
  version: 2

  # If you have testing jobs, put them here...
  # testing:
  #   jobs:

  # All deployment
  deploy:
    jobs:
      - deploy-doc
